
services:
  tor-wireguard:
    build: .
    container_name: tor-wireguard-proxy
    cap_add:
      - NET_ADMIN
    cap_drop:
      - AUDIT_CONTROL
      - AUDIT_READ
      - BLOCK_SUSPEND
      - DAC_READ_SEARCH
      - IPC_LOCK
      - IPC_OWNER
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - MKNOD
      - NET_BROADCAST
      - SETFCAP
      - SETPCAP
      - SYS_ADMIN
      - SYS_BOOT
      - SYS_MODULE
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - SYSLOG
      - WAKE_ALARM
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.25'
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      - WG_HOST=${WG_HOST:-auto}
      - WG_PORT=${WG_PORT:-51820}
      - WG_DEFAULT_DNS=${WG_DNS:-1.1.1.1,1.0.0.1}
      - SOCKS_PORT=${SOCKS_PORT:-9050}
      - TOR_LOG_LEVEL=${TOR_LOG_LEVEL:-notice}
    ports:
      - "${WG_PORT:-51820}:51820/udp"
    volumes:
      - ./data:/data
      - /var/lib/tor
      - /etc/wireguard
    restart: unless-stopped
    networks:
      - tor-net
    dns:
      - 1.1.1.1
      - 1.0.0.1
    logging:
      driver: "none"

networks:
  tor-net:
    driver: bridge
    internal: false
